# Generated by Django 5.0.2 on 2025-06-04 18:41

import alvorada.models
import alvorada.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alvorada', '0002_update_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='foto_relogio',
            field=models.ImageField(blank=True, null=True, storage=alvorada.storage.SupabaseStorage(), upload_to=alvorada.models.get_upload_path),
        ),
    ]
