# Generated by Django 5.0.2 on 2024-03-13 23:56

import django.db.models.deletion
import patricia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField()),
                ('valor_leitura_cozinha', models.DecimalField(decimal_places=3, max_digits=8)),
                ('valor_leitura_banheiro', models.DecimalField(decimal_places=3, max_digits=8)),
                ('foto_relogio_cozinha', models.ImageField(blank=True, null=True, upload_to=patricia.models.rename_file)),
                ('foto_relogio_banheiro', models.ImageField(blank=True, null=True, upload_to=patricia.models.rename_file)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patricia.apartamento')),
            ],
        ),
    ]
