# Generated by Django 5.0.2 on 2025-06-03 17:38

import django.db.models.deletion
import imperial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_leitura', models.DecimalField(decimal_places=3, max_digits=8)),
                ('data_leitura', models.DateField(auto_now_add=True)),
                ('foto_relogio', models.ImageField(blank=True, null=True, upload_to=imperial.models.get_upload_path)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imperial.apartamento')),
            ],
        ),
    ]
