# Generated by Django 5.0.2 on 2025-06-04 18:49

import imperial.models
import imperial.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial', '0002_update_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='data_leitura',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='foto_relogio',
            field=models.ImageField(blank=True, null=True, storage=imperial.storage.SupabaseStorage(), upload_to=imperial.models.get_upload_path),
        ),
    ]
