# Generated by Django 5.0.2 on 2025-11-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial', '0003_alter_leitura_data_leitura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='imperial', max_length=50, unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configurações do Portal',
            },
        ),
    ]
