# Generated by Django 5.0.2 on 2024-02-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doce_vitta.bloco')),
            ],
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField()),
                ('valor_leitura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_relogio', models.ImageField(blank=True, null=True, upload_to='leituras/%m')),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doce_vitta.apartamento')),
            ],
        ),
    ]
