# Generated by Django 5.0.2 on 2024-02-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doce_vitta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartamento',
            old_name='numero',
            new_name='apartamento',
        ),
        migrations.RenameField(
            model_name='bloco',
            old_name='nome',
            new_name='bloco',
        ),
    ]
