# Generated by Django 5.0.2 on 2024-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_vitta', '0002_rename_numero_apartamento_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='bloco',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='apartamento',
            unique_together={('apartamento', 'bloco')},
        ),
    ]
