# Generated by Django 5.0.2 on 2024-02-27 13:42

import doce_vitta.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_vitta', '0003_alter_bloco_bloco_alter_apartamento_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='foto_relogio',
            field=models.ImageField(blank=True, null=True, upload_to=doce_vitta.models.rename_file),
        ),
    ]
