# Generated by Django 5.0.2 on 2024-02-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doce_vitta', '0005_alter_leitura_valor_leitura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='valor_leitura',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
