# Generated by Django 5.0.2 on 2025-06-04 18:49

import tres_coelho.models
import tres_coelho.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tres_coelho', '0002_update_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='foto_relogio',
            field=models.ImageField(blank=True, null=True, storage=tres_coelho.storage.SupabaseStorage(), upload_to=tres_coelho.models.get_upload_path),
        ),
    ]
